---

- name: Cisco show version example
  hosts: all
  gather_facts: false

  tasks:
    - name: run show version on the routers
      ios_command:
        commands: show version | incl Version
        commands: sh log | inc %SYS-5-RESTART
      register: output

    - name: print output
      debug:
        var: output.stdout_lines